<script src="{{ asset('dist/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/oneui.core.min.js') }}"></script>
<script src="{{ asset('assets/js/oneui.app.min.js') }}"></script>
<script src="{{ asset('dist/jquery-ui-1.12.1/jquery-ui.min.js') }}"></script>
<script src="{{ asset('dist/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('dist/moment/locale/es.js') }}"></script>
<script src="{{ asset('dist/bootstrap/js/util.js') }}"></script>
<script src="{{ asset('dist/bootstrap/js/toast.js') }}"></script>
<script src="{{ asset('dist/fullcalendar/js/fullcalendar.js') }}"></script>
<script src="{{ asset('dist/fullcalendar/js/locale/es-us.js') }}"></script>
<script src="{{ asset('dist/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
{{-- <script src="{{ asset('dist/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dist/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dist/datatables/buttons/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('dist/datatables/buttons/buttons.print.min.js') }}"></script>
<script src="{{ asset('dist/datatables/buttons/buttons.html5.min.js') }}"></script>
<script src="{{ asset('dist/datatables/buttons/buttons.flash.min.js') }}"></script>
<script src="{{ asset('dist/datatables/buttons/buttons.colVis.min.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/datatables/buttons/dataTableSelect.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/datatables/buttons-bs4/buttons.bootstrap4.js') }}"></script> --}}
<script src="{{ asset('dist/jquery-number-master/jquery.number.js') }}"></script>
{{-- <script src="{{ asset('dist/simplemde/simplemde.min.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/PACE/pace.min.js') }}"></script> --}}
<script src="{{ asset('dist/jquery-confirm-master/js/jquery-confirm.js') }}"></script>
<script src="{{ asset('dist/bootstrap-validate/bootstrap-validate.js') }}"></script>
<script src="{{ asset('dist/bootstrap-notify/dist/bootstrap-notify.js') }}"></script>
{{-- <script src="{{ asset('dist/jqueryMask/jquery.maskedinput.min.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/jquery.fittext.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/highcharts/highcharts.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/highcharts/modules/exporting.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/highcharts/modules/export-data.js') }}"></script> --}}
{{-- <script src="{{ asset('dist/highcharts/modules/accessibility.js') }}"></script> --}}
<script src="{{ asset('dist/axios.min.js') }}"></script>
<script src="https://js.pusher.com/8.2.0/pusher.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

@stack('scripts')
